src/replication/protocol.rst
=> Simple grammar fixes to protocol.rst

src/api/server/authn.rst, src/config/http-handlers.rst, src/config/http.rst, src/config/intro.rst, src/config/query-servers.rst, src/couchapp/ddocs.rst, src/couchapp/views/intro.rst, src/couchapp/views/joins.rst, src/couchapp/views/nosql.rst, src/fauxton/install.rst, src/intro/futon.rst, src/intro/overview.rst, src/intro/security.rst, src/intro/tour.rst, src/maintenance/performance.rst, src/query-server/javascript.rst, src/whatsnew/0.11.rst
Grammar, spelling, typos, formatting, etc.
=> A number of documentation fixes

src/api/ddoc/common.rst, src/api/ddoc/rewrites.rst, src/json-structure.rst, src/query-server/protocol.rst
Documentation for COUCHDB-2874
=> JS rewrites

src/api/ddoc/views.rst
=> document sending multiple queries to views

src/api/ddoc/views.rst
=> document sorted parameter for view queries

src/intro/overview.rst, src/replication/conflicts.rst, src/replication/protocol.rst
Hey,
while reading the docs I came up with some typo fixes and minor style improvements for the intro and replication chapter.
=> Fix some typos and style in intro and replication chapter

src/api/database/changes.rst, src/json-structure.rst, src/replication/intro.rst, src/replication/replicator.rst
Add material explaining what a selector object is, in the context of a replication document.
Point out that it is one of three options for controlling replication.
Point out that using a selector object is preferable to using a filter function.
=> Describe selector objects as part of a replication document.

src/config/intro.rst
The wording of the paragraph about inline comments is not optimal.
I suggest rephrasing it.
=> Inline comments: Improve phrasing

src/api/server/common.rst
=> _db_updates heartbeat option is a number

src/api/database/changes.rst, src/api/server/configuration.rst, src/config/logging.rst
I adapted the description from that found in the default.ini.
=> Update documentation for logging options

src/api/database/bulk-api.rst, src/replication/conflicts.rst
... as this was removed in 2.0.0
=> Remove references to all_or_nothing for _bulk_docs

src/api/database/find.rst
This replaces #31 which added the Mango docs, but mostly it adds anything from that PR that wasn't already covered in #55 so this version now includes more examples and words in places.  I've also tried to fix at least as many indentation weirdnesses as I've created!
One major difference was that #31 covered indexes with `type=text` which these docs didn't - I've added this content in but I wanted to flag this just in case there's a reason why it shouldn't be included in this context.
=> Additions to _find and _index from original Mango docs PR

src/api/server/configuration.rst, src/config/auth.rst
=> Update documentation for require_valid_user

images/replication-state-diagram.svg, src/api/server/common.rst, src/config/replicator.rst, src/replication/replicator.rst, src/whatsnew/2.1.rst, src/whatsnew/index.rst
"What's New" update includes feature improvements and also an implicit to 3.0
"Replicator" section describing some new behavior and includes a state transition diagram.
Jira: COUCHDB-3324
=> Documentation for the scheduling replicator

src/api/database/find.rst
Remove some text references and update how index is chosen
=> Update mango docs

src/config/http.rst
Documenting the new `X-Frame-Options` header.
=> add X-Frame-Options header documentation

src/api/database/find.rst
Documentation for https://github.com/apache/couchdb/issues/628
=> feat: document stable/update/stale options for _find

src/whatsnew/2.1.rst
=> Update 2.1 What's New document

src/config/intro.rst
Our docs still described the 1.x approach.
Thanks to Luis Urrea who brought this up on our dev mailing list.
Closes apache/couchdb#717.
=> Update for ini file handling under 2.x

src/config/http.rst
Documentation for https://github.com/apache/couchdb/pull/605
=> add prefer: return=minimal documentation

src/api/server/authn.rst
Grammar clarifications, and expanding of response details for `GET /_session` documentation.
=> Clarify and expand on GET /_session response

src/query-server/protocol.rst
General improvements in clarity and grammar, and a few minor corrections (spelling, formatting) for the Query Server protocol documentation.
=> Query Server protocol documentation improvements

src/api/database/find.rst
Adds basic documentation for the execution stats parameter
in Mango/Query.
Corresponding implementation at apache/couchdb#768
=> API documentation for mango execution stats

src/api/database/find.rst
=> add documentation for partial indexes

src/api/database/common.rst
This adds description of a new information block `cluster` and updates description of `update_seq`.
Run linter with  `make check`
Related to apache/couchdb#837 and #164
=> Update description of a database info reply

src/maintenance/performance.rst
=> Improve docs on increasing max file handle limits

src/api/database/find.rst
=> Minor corrections to Explain documentation

src/api/database/changes.rst, src/cluster/setup.rst, src/config/http.rst, src/config/logging.rst
=> Minor changes

src/whatsnew/2.1.rst
=> Update Whatsnew docs to accurately reflect config changes.

src/api/database/bulk-api.rst
Some minor verb number improvement.  And a drive-by removal of the '500' status as a documented status code, since the project seems to have been successfully been cracking down on those as bugs.
=> Minor grammar correction

src/cluster/sharding.rst
This section of the documentation was oddly worded and difficult to follow. This just cleans that up a little.
=> Clean up wording in "Add, then delete" section

src/api/document/common.rst
Update docs to reflect current observed behavior with respect to `multipart/mixed` and `multipart/related` media types.
=> Update multipart/* docs

src/api/database/bulk-api.rst
=> Re-write the bulk doc transaction description to reflect a single mode

src/config/couchdb.rst
In response to https://stackoverflow.com/q/47692745/13860
Somebody please correct me if I'm wrong about this.
=> Mention attachments as they relate to the doc size limit

src/ddocs/views/collation.rst, src/query-server/javascript.rst
There are two links pointing to Apache Git CouchDB repo that are broken.
at src/query-server/javascript.rst
Broken link - https://git-wip-us.apache.org/repos/asf?p=couchdb.git;a=blob;f=share/server/json2.js
New link - https://github.com/apache/couchdb/blob/master/share/server/json2.js
at src/ddocs/views/collation.rst
Broken link - https://git-wip-us.apache.org/repos/asf?p=couchdb.git;a=blob;f=share/www/script/test/view_collation.js;hb=HEAD
New link - https://github.com/apache/couchdb/blob/master/test/javascript/tests/view_collation.js
Fixes apache/couchdb-documentation#223
=> Fix two broken links in javascript.rst and collation.rst

src/maintenance/performance.rst
Added information, how to increase connection limit.
- [] Documentation is written and is accurate;
- [] `make check` passes with no errors
- [] Update [rebar.config.script](https://github.com/apache/couchdb/blob/master/rebar.config.script) with the commit hash once this PR is rebased and merged
=> Added information, how to increase connection limit

src/api/database/bulk-api.rst
Document new endpoint `_design_docs` to allow to return a JSON structure of all of the design documents in a given database.
see https://github.com/apache/couchdb/pull/1110
https://github.com/apache/couchdb/issues/1100
https://github.com/apache/couchdb/pull/1110
https://github.com/apache/couchdb/issues/1100
=> Document new endpoint _design_docs

src/api/server/common.rst, src/config/http-handlers.rst, src/intro/security.rst
=> Document changed /_restart behaviour

src/api/server/common.rst
=> Document /_up endpoint

src/whatsnew/2.2.rst
=> Add 2.2.x 'What's New' template

src/install/upgrading.rst
Some lovely improvements to our upgrade documentation, if I do say so myself.
=> Improve instructions on upgrading to latest CouchDB releases

src/api/server/common.rst
=> Update _stats and _system sections

src/conf.py
=> bump version

src/whatsnew/2.2.rst
Prominent mistake, needs fixing
=> 2.2 release notes spelling error

src/install/upgrading.rst
=> set perms correctly on file copy

src/api/database/find.rst
=> Remove  operator from CouchDB base documentation

src/api/database/common.rst
=> Fix apache/couchdb#1485

src/config/replicator.rst
As revealed by investigation of apache/couchdb#1557.
Source: https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_api_wrap.erl#L479
=> Improve documentation on repl connection_timeout setting

src/api/database/partitions.rst
=> Review and update partition content.

src/config/replicator.rst
Detailed a bit more the replication scheduler parameters.
The changes are in section 3.9, replication configuration.
This pull requests fixes issue #344 I previously opened.
=> Trying to improve the replication scheduler configuration parameters (fixes apache/couchdb#344)

src/config/cluster.rst
=> Document the new seedlist config setting

ext/configdomain.py, ext/github.py, ext/httpdomain.py, ext/linter.py, src/conf.py
Formatting fixes from applying the Python Black code formatter: https://github.com/ambv/black
These will be necessary to make code format checking part of the main CouchDB Makefile. (PR forthcoming)
=> Python formatting fixes from black

src/api/server/common.rst
I've added documentation about some query parameters for the `GET /_all_dbs` endpoint. I've tested that these parameters work on CouchDB 2.3.0.
=> Add some query params to the GET /_all_dbs endpoint

.gitignore, src/api/document/common.rst, src/best-practices/documents.rst, src/best-practices/index.rst, src/best-practices/views.rst
In progress. So far:
* How to handle stats aggregation
* How to design for replication
* How to update views live without breaking production (a popular one!)
* Adding client-side security)
=> Migrate more howtos from MoinMoin

src/maintenance/backups.rst, src/maintenance/index.rst
@flimzy i'm on a roll, expect a bunch more of these
if you're curious why, see https://github.com/apache/couchdb/issues/1813
=> Add backup information, port from MoinMoin wiki

src/best-practices/index.rst, src/best-practices/iso-date.rst
@flimzy content from https://wiki.apache.org/couchdb/IsoFormattedDateAsDocId (now deleted)
=> Migration of MoinMoin ISO date content

src/cluster/sharding.rst
Trivial formatting fix, blocks were not rendering into HTML at all
=> Fix block formatting for mm docs

src/setup/cluster.rst
=> Improve node naming docs for cluster setup

src/cluster/databases.rst, src/cluster/sharding.rst, src/config/cluster.rst
Wherever we mention the `placement` option, make it clear that this will override the default `n` value.
Closes #374 .
=> Improve placement docs, closes #374

src/api/server/common.rst, src/cluster/sharding.rst, src/config/index.rst, src/config/resharding.rst
Related to the main PR: https://github.com/apache/couchdb/pull/1972
=> Add _reshard HTTP API reference documentation

src/api/server/configuration.rst
goes with https://github.com/apache/couchdb/pull/2034
=> feat: remove unused config var from example

src/install/unix.rst
Related issue https://github.com/apache/couchdb/issues/2069
=> Add erlang 22 to the list of supported versions

src/api/database/common.rst, src/api/partitioned-dbs.rst, src/partitioned-dbs/index.rst
This is documentation for the new partitioned databases feature. It covers the new APIs as well as provides a guide on actually using the feature.
Main feature PR: apache/couchdb#1789
Documentation is written and is accurate;
make check passes with no errors
=> Update database partitions with review changes

src/config/http.rst
=> Fix stray reference to couch_httpd_auth

src/install/unix.rst
Just a small fix to improve the text and to install the repo key in a more secure manner.
=> Improve UNIX binary install even more

src/config/index.rst, src/config/indexbuilds.rst
Brief documentation on configuring the system that performs background indexing jobs
https://github.com/apache/couchdb/pull/1910
=> Documentation for background indexing

src/api/database/bulk-api.rst
Impossible to get 417 response code from `_bulk_docs` endpoint. The only way is to use `all_or_nothing` field, but the release note states that it is not supported anymore on version 2.0. 
http://docs.couchdb.org/en/latest/whatsnew/2.0.html#upgrade-notes
1. Create a validation document:
```
{
"_id": "_design/validation",
"validate_doc_update": "function(newDoc) { 
if(newDoc.sales > 20) {
throw({ forbidden: 'Impossible value.'})
}
}"
}
```
2. Update an existing document with invalid value:
```
{
"docs": [
{
"_id": "sales1",
"_rev": "1-156c36a09be5d5ddfaf095f8add6d5da",
"sales": 25
}
]
}
```
https://github.com/apache/couchdb/issues/2209
none
=> Remove 417 response codes

src/install/unix.rst
=> Add sudo to apt-key, closes #450

rfcs/013-node-types.md
A new RFC to implement heterogeneous node types for CouchDB 4
=> [RFC] Introduce CouchDB node types

src/api/ddoc/views.rst
In https://github.com/apache/couchdb/pull/2338 the way POST view works is altered so that the same functionality is available as in GET view.
This commit updates the POST view documentation to reflect this new behavior.
This depends on https://github.com/apache/couchdb/pull/2338 .
Execute the tests seen in https://github.com/apache/couchdb/pull/2338 .
* https://github.com/apache/couchdb/pull/2338
=> Update POST for view

src/replication/index.rst, src/replication/intro.rst
Small clarifications of existing docs.
=> clarify replication

src/best-practices/forms.rst
=> request argument fixed in update function (req instead of request)

src/config/resharding.rst
Some entries were stale and others were missing
=> Update resharding config section

src/setup/cluster.rst, src/setup/single-node.rst
This covers the improvements from apache/couchdb#2398 that @janl made.
=> Document improvements to setup API

src/api/server/common.rst, src/whatsnew/3.0.rst
=> Document GET /_node/{nodename}

src/api/database/compact.rst, src/cluster/sharding.rst, src/cluster/theory.rst, src/config/auth.rst, src/config/cluster.rst, src/config/couchdb.rst, src/config/logging.rst, src/config/misc.rst, src/whatsnew/3.0.rst
Closes #460.
There's a couple of new things missing I didn't add for time...but I checked all of the changes to `default.ini` since 2.3.1 and this is all of them.
=> Incorporate new config default settings

Jenkinsfile
because waiting an hour for Travis is ridiculous.
=> New Jenkinsfile for faster testing

src/whatsnew/3.0.rst
Add Fauxton updates to v3.0 release notes
Fixes #493
=> Add Fauxton updates to v3.0 release notes

src/api/ddoc/search.rst, src/api/server/common.rst, src/ddocs/search.rst, src/install/index.rst, src/install/search.rst, src/whatsnew/3.0.rst
Basic installer docs for Clouseau.
Follow one of the install processes and then go to the search user guide and see if you can create a search index.
Closes #474
=> Document Clouseau install process

src/whatsnew/3.0.rst
Minor format fix for github issue link in 3.0 whatsnew. It was not correctly rendered as a link.
N/A
N/A
=> Minor format fix for github issue reference in 3.0 whatsnew

src/api/partitioned-dbs.rst
=> Replace foo with sensor-260

src/api/server/common.rst
=> Fixes /_reshard/jobs POST route in Docs

src/install/docker.rst
=> Fix docker version

.github/PULL_REQUEST_TEMPLATE.md
The checklist includes items about writing documentation and running automated tests.
The first item is not applicable as most of the commits in this repo are supposed to be doc changes and the automated tests are run for every PR via the Jenkins CI so it's redundant to have a checkbox in the PR summary.
This change removes those two non-applicable items.
=> Remove unnecessary items from the PR checklist

src/install/unix.rst
=> Added setup of admin for Redhat/CentOS

src/conf.py, src/whatsnew/3.1.rst, src/whatsnew/index.rst
After this, I'll fork 3.0.1 and cherry-pick just the 3.0.1 changes to a new branch.
=> 3.1.0 release notes

src/install/freebsd.rst, src/install/snap.rst, src/install/unix.rst, src/install/upgrading.rst, src/whatsnew/3.0.rst
As requested in #501 
I also slipped in a slight improvement to the snap channel text.
=> Improve admin user requirement warnings, closes #501

src/install/snap.rst
=> feat: clarify paths on snap

src/api/database/changes.rst
Document EOL for continous feed with limit.
=> limit and continous mode

src/replication/intro.rst
=> Fix a typo

src/maintenance/compaction.rst
This PR clarifies 2 points about scheduling window parameters in order to avoid confusion as in https://github.com/apache/couchdb/discussions/2997.
=> Improve explanations about scheduling windows

src/intro/tour.rst
- Fixes a couple of typos and formatting issues in the tour
- Add a note to the Mango section that using an index is strongly recommended, even if it "works" without one
- Expands the final Mango example slightly to really make it do what it says (get all movies in the 1980s)
If you want to see the changes, run `make html` and open `/build/html/intro/tour.html` in a browser. It’s just text changes, and `make check` doesn’t complain.
=> Documentation: small improvements to the tour

src/cluster/theory.rst
=> Inline code block

src/config/query-servers.rst
`s/does not runs/does not run/`
=> Fix typo in query-servers.rst

rfcs/016-fdb-replicator.md
Replicator design RFC for CouchDB 4.x
=> [RFC] Replicator Implementation for CouchDB 4.x

src/conf.py
=> Bump version number to 3.1.1

src/config/auth.rst, src/config/indexbuilds.rst, src/replication/conflicts.rst
The original #597 included both bits that everyone seemed to agree with, and bits that need a bit more discussion before settling.
That pr has now been split into two, this one is the more straightforward one.
Switch to using more inclusive nomenclature
=> More inclusive terminology pt 1

src/cluster/index.rst
Added a short description of Standalone and Clustermode which should make clearer what the purposes of the modes are. I tried to sketch it to make the process easier.
Give the text to someone who has no in-depth knowledge of couchdb.
=> Description of Standalone vs Cluster

src/api/database/bulk-api.rst, src/api/database/find.rst, src/api/ddoc/views.rst, src/conf.py, src/ddocs/views/pagination.rst
Documentation for pagination API.
`make check` should be sufficient
* [RFC-014 : Add pagination proposal](https://github.com/apache/couchdb-documentation/pull/530)
* [apache/couchdb#2870 : Implement paginated API](https://github.com/apache/couchdb/pull/2870)
* [apache/couchdb#2896 : Fix handling of limit query parameter](https://github.com/apache/couchdb/pull/2896)
* [apache/couchdb#2904 : Add support for previous bookmark](https://github.com/apache/couchdb/pull/2904)
=> Document pagination API

src/api/ddoc/views.rst
=> typo correction in the "stale" documentation

src/intro/curl.rst
single quotes -> single double-quotes
=> Fix a typo in curl.rst

src/install/mac.rst
=> Fix broken link.

src/ddocs/views/collation.rst
=> Fix Unicode Collation Algorithm link

src/ddocs/views/intro.rst, src/maintenance/compaction.rst
While learning CouchDB I noticed that the documentation was missing the exact rest endpoints and json for creating and querying views. I added two curl commands to give a first impression how to create and use views from an application.
Read the changed text and try out the two new curl commands yourself.
=> Improved documentation for creating and querying views

rfcs/017-fair-share-scheduling.md
Discussed on the [ML](https://lists.apache.org/thread.html/rebba9a43bfdf9696f2ce974b0fc7550a631c7b835e4c14e51cd27a87%40%3Cdev.couchdb.apache.org%3E)
Based on the Fair Share Scheduler paper by [Judy Kay and Piers Lauder](https://proteusmaster.urcf.drexel.edu/urcfwiki/images/KayLauderFairShare.pdf)
=> [rfc] Fair Share Replication Scheduler

src/config/replicator.rst, src/replication/replicator.rst
A short description on how the algorithm works along with the configuration sections.
Main PR: https://github.com/apache/couchdb/pull/3364
=> 3.x fair share scheduler documetation

src/ddocs/ddocs.rst
Describes the structure of a design document in a newbie-friendly way.
Please check that the example I added is correct. I've tested it to the best of my abilities but would like someone else to take a look at it too.
Related to #359 and #429
=> Add description of a ddoc structure

src/install/mac.rst, src/install/windows.rst, templates/pages/index.html
=> couchdb.org --> couchdb.apache.org

src/cluster/index.rst, src/cluster/troubleshooting.rst
This is a port of the `weatherreport` README
https://github.com/apache/couchdb/pull/3312
=> Port weatherreport README to cluster troubleshooting section

src/api/document/common.rst
=> Warn against use of new_edits, closes #390

src/api/server/common.rst, src/replication/replicator.rst
As the description says, closes #232
=> Document create_target_params, closes #232

src/config/couch-peruser.rst
=> Document couch_peruser q, closes #234

src/api/database/find.rst, src/setup/cluster.rst
=> fix formatting, closes #310

src/config/http.rst, src/setup/cluster.rst
=> 2.x becomes 2.x/3.x where appropriate, closes #602

src/config/intro.rst
=> Add alternate location for local.ini for macOS, closes #575

src/install/unix.rst
=> Properly call out CentOS/RHEL 8, closes #551

src/api/database/changes.rst
Clarify heartbeat vs. continuous, closes #522
=> Clarify heartbeat vs. continuous, closes #522

src/install/search.rst
=> Make clearer Clouseau requires Java 6 < x < 8

src/api/database/find.rst
* Improve use_index documentation, closes #350
* Clarify condition operators, closes #380 
* Clarify comparison ops, closes #381
* Include conflicts key, closes #391
=> Improve mango docs

src/maintenance/compaction.rst
Closes #321 . All this does is move the automatic compaction section above the manual compaction section.
=> Reorganise db/view compaction section, closes #321

src/ddocs/views/index.rst
Improve reading by fixing a little typo error.
=> Fix typo in ddocs/views

src/maintenance/compaction.rst
Related PR in apache/couchdb is https://github.com/apache/couchdb/pull/3600
=> Document 3.2 new smoosh defaults

src/replication/replicator.rst
Implementation PRs:
https://github.com/apache/couchdb/pull/3599
https://github.com/apache/couchdb/pull/3586
=> Document the new {"auth": {"basic": ...}} replicator basic auth format

src/best-practices/jsdevel.rst
=> Update advice re: old JS version, closes #624

src/config/misc.rst
3.1.x version of https://github.com/apache/couchdb-documentation/pull/683
=> Feat/csp 3.1.1

src/cve/2021-38295.rst
nothing to see here in the 3.1.x version of https://github.com/apache/couchdb-documentation/pull/685 either
=> feat(cve): commit placeholder

src/intro/curl.rst
=> fixes typo

src/api/server/authn.rst
Closes https://github.com/apache/couchdb/issues/3811
=> fix(jwt): we follow the spec now

src/install/unix.rst
=> Update link to spidermonkey

src/install/mac.rst
Updating Homebrew install description
=> Update Homebrew installation

src/api/server/common.rst
https://github.com/apache/couchdb/pull/3832
=> skip/limit won't work properly when _design docs exists

src/api/server/common.rst
https://github.com/apache/couchdb/pull/3969
=> Fix skip and limit parameters for GET `_all_dbs` and `_dbs_info`

src/api/ddoc/views.rst
=> Fix the typo

src/config/intro.rst
ini files in `*.d` directories are sorted by filename.
=> doc: describe ini file ordering

src/cluster/sharding.rst
As discussed on Slack: https://couchdb.slack.com/archives/C49LEE7NW/p1651683467305709?thread_ts=1651590185.953189&cid=C49LEE7NW
=> Fix quorum description for view queries

src/best-practices/reverse-proxies.rst
=> Update reverse proxy config for nginx

src/cluster/theory.rst
With one replica you can have more than one node so long as you have multiple shards.
=> Remove statement about single replica scale

src/config/auth.rst, src/intro/security.rst
Lowers the friction for new users configuring authorization to be secure and performant.
Check that the sentences read correctly, and the link goes to the right place.
=> Updates & links info on # iterations for authorization

rebar.config, src/docs.app.src
=> Migrate to rebar3

src/config/auth.rst, src/whatsnew/3.2.rst
Please merge, if https://github.com/apache/couchdb/pull/4153 is merged.
=> config section for require_valid_user is only [chttpd]

src/config/auth.rst
Document the new config parameter `hash_algorithms` from PR https://github.com/apache/couchdb/pull/4140
=> Document new hash_algorithms config key

src/api/server/common.rst, src/json-structure.rst
Related to https://github.com/apache/couchdb/pull/4144
=> Add replicator bulk_get stats
