apache/couchdb-documentation

src/cluster/databases.rst
src/cluster/index.rst
src/cluster/nodes.rst
src/cluster/setup.rst
src/cluster/sharding.rst
src/cluster/theory.rst
src/contents.rst

This is basically my couchdb-crazy rep, converted and modified.
The documentation is not done with this, but it is a base to build on.
This is all I have on 2.0, so if anyone wants to fork this branch and continue building on it before merging, please do so :)

A base to build on for 2.0

---

src/replication/replicator.rst

Adds documentation describing what happens when you try to modify a triggered continuous replication.

Document modifying triggered replication documents

---

src/api/ddoc/views.rst

The fact that startkey_docid depends upon startkey isn't explicitly mentioned, and has caused confusion in issues like https://issues.apache.org/jira/browse/COUCHDB-834

note link between startkey and startkey_docid

---

Makefile

The [[ operator is a bashism, and fails with POSIX shells (such as dash),
replace it with a simplier version that does the same thing, without the
unnecessary $(shell) nesting.

Fix bashism in Makefile

---

src/api/database/bulk-api.rst

COUCHDB-2578  _all_docs 'keys' parameter not documented

Fix for COUCHDB-2578

---

src/api/database/bulk-api.rst

To be consistent with text at line numbers 302-303:
- _id field is omitted in request
- an automatically generated _id is returned by CouchDB

To automatically generate the _id should be omitted

---

src/config/replicator.rst
src/replication/replicator.rst
src/whatsnew/2.0.rst

Remove configurable replicator db name functionality

---

.gitignore

A `__pycache__` directory appeared after making the docs with a Python3 version of Sphinx. Python3 stores cache files in that directory instead of *.pyc files. Should be added to .gitignore.

Ignore Python3 __pycache__ dir

---

.travis.yml
ext/httpdomain.py
src/api/basics.rst
src/api/database/changes.rst
src/api/database/index.rst
src/api/ddoc/render.rst
src/api/ddoc/views.rst
src/api/document/common.rst
src/api/server/common.rst
src/conf.py
src/config/compaction.rst
src/config/couchdb.rst
src/config/externals.rst
src/config/http.rst
src/config/intro.rst
src/replication/conflicts.rst

* Remove JSON as default highlight language from conf.py, so Sphinx does not assume all non-marked code blocks are JSON per default.
* Use valid HTTP
* add ` HTTP/1.1` to each request line
* Pygments' http lexer currently does not recognize the COPY method, so disable highlighting for blocks that use COPY.
* Minor changes with shell code-blocks - shell-sessions and shell-scripts require different lexers.

COUCHDB-3068 - Fixes to make docs build with Sphinx 1.4

---

src/api/database/find.rst
src/api/database/index.rst

API reference documentation for the new _find and _index endpoints.
Credit to this primarily goes to @KimStebel who wrote the original content at [https://github.com/cloudant-labs/slate].
This is heavily based on the Cloudant Query documentation, with references to text indices removed.

API documentation for _find and _index endpoints

---

src/api/document/common.rst

This changes update sequences type to string, and add a description of
the new_edits option for PUT requests.
Fixes COUCHDB-3136.

Update document API for 2.0.0

---

src/api/database/find.rst

Man pages do not support table row spanning, so don't do it.

Remove row-spanning in _find documentation

---

src/api/server/configuration.rst
src/config/auth.rst
src/config/couchdb.rst

Introduce `couchdb/users_db_suffix` config key
Remove distinction between clustered and local users databases
configuration. We remove following configuration options and replace
them with `couchdb/users_db_suffix`:
- `chttpd_auth/authentication_db`
- `couch_httpd_auth/authentication_db`
This is a companion PR for https://github.com/apache/couchdb-couch/pull/198

Document users db suffix

---

src/install/unix.rst

It prevents docs from being built currently

Fix an asterisk escape in unix install

---

src/config/query-servers.rst

Update documentation with correct description of os_process_limit
parameter function, correct default value, and hints for typical
production values.
COUCHDB-3238

Fix os_process_limit documentation

---

.travis.yml
Makefile
make.bat

According to the latest failed builds, sphinx needs at least Python 2.7 or 3.4 to build.
This is simply an attempt to apply the solution suggested by sphinx. I don't know if there is any other impact to this repository - please review :)

Update python versions to 2.7/3.4

---

src/install/index.rst

Stress the fact that the “Single-Node-Setup” creates the system databases for you. Add how single node setup can be done without using the wizard.

install/index.rst: More details on Single-Node-Setup

---

src/api/server/configuration.rst
src/config/couchdb.rst
src/config/http.rst

Add documentation for the new `max_http_request_size` parameter

---

src/api/document/common.rst

The previous version mentions 'If-Match' as an "alternative to rev query
parameter", but doesn't mention the rev query parameter. This fixes that
discrepency, and further elaborates on how the rev parameter is used and
when it is necessary.

Clarify use of 'rev' query parameter in document PUT

---

src/config/couchdb.rst

Bring back the correct implementation of max_document_size

---

.travis.yml
Makefile

As discussed on the mailing list, this removes the PDF and info
builds from the default build.
Fixes COUCHDB-3329
Relates to apache/couchdb:3329-kill-pdf-texinfo branch.

Remove pdf and info builds from default target

---

src/couchapp/ddocs.rst

There should not be two sets of return semantics
for one function...but in the meantime, this
hopefully keeps people from hurting themselves...

Clarify provides() usage in _list function

---

src/query-server/javascript.rst

The query server only copies `lib` if they are inside `views`, but `require` does start at the root of the design document.
Using `lib/security` would mean that there is a `lib` entry at the root of the design document.

Use the proper location for `require` example

---

src/cluster/theory.rst

Fixes a minor to/too typo and improves the English for readability.

Tiny tidy-up in the Theory Chapter

---

src/api/document/attachments.rst

These headers were completely misdocumented, even for Couch 1.6.  But
they've all been removed entirely for Couch 2.0.0, according to my testing.

Update docs for PUT attachments

---

src/api/document/attachments.rst

These headers were completely misdocumented; the result of an apparent
copy-and-paste from the GET headers documentation.

Update docs for PUT attachments in 1.6.x branch

---

src/api/database/common.rst
src/api/database/compact.rst
src/intro/curl.rst
src/intro/security.rst
src/maintenance/compaction.rst
src/replication/protocol.rst
src/whatsnew/2.0.rst

Previously, the new behavior (that instance_start_time is always "0") was
mentioned only in one place. This updates it throughout the documentation.

Update all references to instance_start_time

---

src/api/server/common.rst
src/replication/replicator.rst

Document these endpoints:
* _scheduler/docs/{replicator_db}
* _scheduler/docs/{replicator_db}/{docid}
Update replicator example due to the API change in how single replicator doc
info is retrieved.
Issue https://github.com/apache/couchdb/issues/506

Update docs related to _scheduler/docs/{db}/{docid} endpoint

---

src/conf.py
src/cve/index.rst
src/fauxton/install.rst
src/whatsnew/2.0.rst
src/whatsnew/2.1.rst
templates/help.html

This PR updates our actual documentation (as opposed to contributing/issue/pr files) with pointers to the new GitHub Issues link rather than JIRA. It includes a macro `ghissue` similar to the original `issue` for quick-linking to new issues.
`make check` passes.

Update documentation to point to GitHub issues for new issues

---

src/api/document/common.rst

Fixing documentation for `meta` parameter to correctly describe what this parameter encompasses.

Correcting `meta` parameter documentation

---

src/install/freebsd.rst
src/install/index.rst
src/install/mac.rst
src/install/setup.rst
src/install/unix.rst
src/install/upgrading.rst
src/install/windows.rst

This adds documentation for the new couchup utility. It also reorganizes
the installation documentation order, and includes explicit reminders
in every installation section to follow the first-time setup steps.
We've been getting a LOT of drive-bys on IRC/Slack asking why there are
endless errors about _users and _replicator in the logfiles, and I
suspect it's because that section is buried on the same page as the table
of contents for the installation section.

Document new couchup utility, improve installation documentation

---

src/api/ddoc/common.rst

Just replace a misleading note regarding `COPY` operation on Design documents.

Update confusing note on dd copy operation

---

src/api/database/common.rst
src/whatsnew/2.0.rst

as it relates to a different resource.
Note: We used to send ETag for this in previous releases, so it's
technically a regression even though we accidentally fix a spec
violation.
Closes apache/couchdb#620

POST /dbname should not return ETag response header

---

src/api/database/find.rst

Also update the data type for a few fields, and mark `selector` as required.
This corrects the documentation for the _find endpoint to reflect that the parameters must be sent via the JSON body, rather than as query parameters.

Find API uses JSON body, not query parameters

---

src/install/docker.rst
src/install/index.rst
src/install/mac.rst
src/install/setup.rst
src/install/snap.rst
src/install/unix.rst
src/install/windows.rst

This PR:
* updates the Mac and Windows installation instructions
* advertises the .deb/.rpm packages for Unix
* includes separate pointers for the Docker and snapstore convenience binaries
* corrects a few minor misspellings.
Closes #141.

Advertise convenience binaries for installation

---

src/api/server/common.rst
src/cluster/setup.rst
src/install/setup.rst
src/whatsnew/2.1.rst

Documents the new `enable_single_node` action as well as the required `node_count` parameter. Also, adds the full syntax for the `/_cluster_setup` endpoint to the HTTP API reference.
Closes apache/couchdb#593

Fully document _cluster_setup endpoint for 2.1

---

src/cluster/theory.rst

This is an update for a section on a cluster configuration, removing mention of outdated configuration parameters and specifying how number of reads and writes before a success code is returned defined in a cluster.
apache/couchdb#837

Update info on cluster configuration

---

src/config/replicator.rst

The new value is 5 but used to be 10, which makes more sense with the new
scheduling replicator behavior.
Issue #810
This is associated with this PR:
https://github.com/apache/couchdb/pull/843

Updated documentation for new replicator retries_per_request value

---

src/config/replicator.rst

Fix typo in config/replicator.rst

---

src/api/server/authn.rst
src/config/http.rst
src/config/services.rst
src/whatsnew/1.6.rst

We fixed this in https://issues.apache.org/jira/browse/COUCHDB-3203 but never updated the docs to match.

httpd->chttpd for 2.x proxy auth and SSL

---

src/maintenance/compaction.rst

The current documentation suggests the compacter is disabled by default, as by having its options commented out in .ini files. As of 2.1+ the compacter is enabled by default, per @wohali :
> [freenode#couchdb] Wohali: compaction is now enabled by default in 2.1.0 and up
Fixes #170

compacter is enabled by default.

---

src/maintenance/performance.rst

Our documentation on increasing fd limits could be a bit clearer. Here's a patch.

Improve docs on bumping fd limits

---

src/api/database/common.rst
src/cluster/databases.rst
src/config/cluster.rst
src/config/index.rst

We were missing the entire config section for `[cluster]`. We also didn't document you can specify `q` when creating a DB.
Oops.

Document PUT /{db}?q=# and cluster config settings

---

src/config/auth.rst

Changed reference from x_auth_roles to x_auth_token to match section.

Fix typo in auth docs

---

src/whatsnew/2.1.rst

Also moved the upgrade notes to the start to be more consistent with previous release note formatting.

Add 2.1.1 release notes

---

src/api/document/common.rst

Followup to #186, and specifically https://github.com/apache/couchdb-documentation/pull/186#pullrequestreview-72260141, to make it easier to find the "copy to existing document" instructions.

Make "copy to existing document" capabilities more explicit.

---

src/api/document/attachments.rst

This updates the docs to reflect that it is possible to create an empty document with `PUT /{db}/{docid}/{attname}`.  Example with 2.1.0:
```
$ curl -v -X PUT http://admin:abc123@localhost:6002/foo/asdf/asdf.txt -H 'Content-Type: text/plain' -d 'Foo'
*   Trying ::1...                                                                                                                                                                                                                
* TCP_NODELAY set                                                                                                                                                                                                                
* Connected to localhost (::1) port 6002 (#0) …
```

Update the PUT {attachment} docs to reflect observed behavior.

---

src/api/document/attachments.rst

My tests with 1.6.1, 2.0.0 and 2.1.0 all suggest that the `Content-MD5` header is not set in GET or HEAD responses when querying attachments.  Perhaps this was removed after the `ETag` header was added, as they are practically duplicates?
Example, from 2.1.0:
```
$ curl -v -X GET http://admin:abc123@localhost:6002/foo/foo/foo.txt
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 6002 (#0)
* Server auth using Basic with user 'admin'
> GET /foo/foo/foo.txt HTTP/1.1
> Host: localhost:6002
> Authorization: Basic YWRtaW46YWJjMTIz
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: CouchDB/2.1.0 (Erlang OTP/17)
< ETag: "ENGoH7oK8V9R3BMnfDHZmw=="
< Date: Thu, 26 Oct 2017 21:31:41 GMT
< …
```

Remove mention of Content-MD5 header, which isn't present

---

src/config/http.rst

A huge oversight - the last attempt at fixing this didn't catch everything.
Couple of minor grammar mistakes fixed, too.

Clarify chttpd vs. httpd for bind_address/port

---

src/maintenance/performance.rst

The "DELETE operation" section of maintenance/performance.rst is unclear. This PR replaces "B+Tree's" with "B+Tree" and otherwise adds a few instances of "the" for clarity.

Modify articles, commas, and spelling in the 'DELETE operation' section for clarity.

---

src/install/unix.rst

Rather than adding a note block, I decided to duplicate the block, since people cut & paste blindly out of instructions.

Correct RHEL instructions, fixes apache/couchdb#956

---

src/whatsnew/2.1.rst

user@ reported that the change to the default node name tripped them up. Would be wise to add the remediation steps to the release notes.

Clarify change to default node name in 2.1.1

---

src/api/server/configuration.rst
src/config/intro.rst

AFAICT, the new `_config/_local` feature was only mentioned in the What's New document. This adds explicit mention a couple more places in the docs.

Mention _config/_local in docs

---

src/api/server/common.rst

This is based on my observations; I don't know if it's complete.

Document the 'info' field of the scheduler doc

---

src/api/document/attachments.rst

The old version referred to the literal string `attachment`, but it's called `attname` in the template.

Minor formatting improvement

---

src/api/database/common.rst

Takes some inspiration from the old wiki: https://wiki.apache.org/couchdb/HTTP_Document_API

Better documentation for 'batch mode'

---

src/api/document/attachments.rst

... Unless for some reason this endpoint is excluded for this header?

Mention X-Couch-Full-Commit header for PUT ..{att} endpoint

---

src/api/server/authn.rst
src/config/http.rst

In CouchDB 2.0 we moved to chttpd for the cookie and default authentication handlers. We updated most of the documentation but overlooked the part where we advised folks on the configuration of custom handlers. This fixes that oversight.
See apache/couchdb#1054

Use the correct module for cookie and default auth

---

src/replication/protocol.rst

The link to couch_replicator_utils.erl is broken and should point to github code. 
In the new code, couch_replicator_utils.erl does not contains the ID generation logic so the reference is update to point to couch_replicator_ids.erl where de ID is build.
Fixes apache/couchdb-documentation#221

Fix broken link in Generate Replication ID section

---

src/install/troubleshooting.rst

There is this issue with the missing dependency. How about adding the workaround to the documentation until resolved.
#979 (https://github.com/apache/couchdb/issues/979)

Adding osx dependencie issue to documentation

---

src/config/intro.rst

The existing `couchdb` start script hard-codes the arguments to
`-args_file` and `-config`. Although it is possible to copy this
script and modify it, or modify it in place, that is less than ideal
and can lead to all kinds of difficulties.
This PR documents the user-facing capabilities introduced by the corresponding PR on the `couchdb` repository.
apache/couchdb/pull/1095

Document changes to the `couchdb` start script

---

src/api/server/common.rst

Replication between 2 couchdb nodes with custom headers is implemented, but not present in the documentation. This commit adds that.

added header info to replication api

---

src/api/server/common.rst

Fixed the incorrect headers documentation I added in the replication api

fixed source and target database instructions in the replication api

---

src/cluster/setup.rst

This pull request fixes a typo in the cluster/setup.rst file where a `r` was missing from `Your CouchDB cluster` and it said `You CouchDB cluster`. This will give users a better user experience while they read through the documentation.
I created the PR because I read the documentation and was confused by that sentence and I cared enough about it to create a Pull Request so that other users will have a better experience then I did.

fix(typo): fix a typo in setup.rst

---

src/install/unix.rst

Fixed Mozilla SpiderMonkey (1.8.5) dependency link. Currently it is pointing to a "404 page not found". Now it will point to correct documentation of Mozilla SpiderMonkey.
Open the link.
#248

Fixed Mozilla SpiderMonkey (1.8.5) dependency link.

---

src/config/http.rst

Document the correct node-local port.

Use the correct node-local port

---

src/cluster/sharding.rst

See apache/couchdb#1198 for detail.
Even without apache/couchdb#1199 landing, this will at least stop directing people to use a feature we never intended to make available.
This whole page needs a rewrite; @garbados has agreed to take a look in the future. In case that doesn't land for 2.2.0, I wanted to get this quick fix in place instead.

Remove mention of Fauxton on port 5986

---

src/cluster/theory.rst

I found the documentation about read and write quorums for a cluster mode DB confusing. I think this edit makes things a bit more clear (though I don't love the wording).
This came from a Slack conversation which you can find here if curious: https://couchdb.slack.com/archives/C49LEE7NW/p1519761842000347

Suggested edit to make clear what a quorum actually represents.

---

src/config/replicator.rst
src/whatsnew/2.2.rst
src/whatsnew/index.rst

New `auth_plugins` section in config API
Mention experimental session plugin status in whatsnew for 2.2.x

Replication plugin and session support

---

static/css/rtd_theme.css

Fixes #201.
Note that, in my testing, prefixing the list with:
```rst
.. rst-class:: open
```
may be necessary to force the double-spacing, especially if the list is not internally double-spaced already, or has lines that are only one line long.

Fix whitespace in bulleted lists

---

src/api/database/changes.rst

Added the seq_interval parameter description as suggested by @wohali  in #230 with minor changes.
A note has been added referencing the improvement gained by other projects when using this parameter
This PR fixes #230

Document seq_interval parameter

---

src/api/local.rst

This PR is an amend for PR #260 
- Corrects _local_docs example by setting offset and total_rows to null
- Removes ETAG references in _local_docs documentation

Fix _local_docs examples and remove ETAG references

---

src/api/database/bulk-api.rst
src/api/ddoc/views.rst

Document new feature for multiple queries against POST `/{db}/_all_docs/queries`. This allows to execute multiple specified built-in view queries of all documents in specified database. This enables you to request multiple documents in a single request, in place of multiple POST `/{db}/_all_docs` requests.
The multiple queries are also supported in `/db/_local_docs/queries` and `/db/_design_docs/queries` (similar to `/db/_all_docs/queries`).
In addition, the multiple queries against view are supported in newly introduced endpoint `/{db}/_design/{ddoc}/_view/{view}/querie`
see https://github.com/apache/couchdb/pull/1032/
Issue #820
https://github.com/apache/couchdb/issues/820
https://github.com/apache/couchdb/pull/1222
- [] Update …

Queries endpoint support

---

src/cluster/setup.rst

- When doing cluster_setup via api or wizard we need to make changes in vm.args as all nodes should have a unique name (mentioned in the file comments but not in the cluster setup documentation)
- executing _cluster_setup api with enable_cluster the second time gives error response on the coordination node when adding nodes to cluster hence is not required causes failure
- only add_node action is required from _cluster_setup api on  coordination node
- Added cluster setup verification docs

Fix _cluster_setup api | couchdb node name changes | verify cluster setup  

---

src/api/database/bulk-api.rst

The POST _bulk_get endpoint was not documented, and not even listed in the API reference. I have added a short description with an example.
The POST _bulk_get endpoint should appear in the API reference.
Fixes #246

Add the POST _bulk_get endpoint

---

.travis.yml
src/best-practices/forms.rst
src/best-practices/index.rst
src/best-practices/jsdevel.rst
src/index.rst

This is the start of my and @flimzy's "ditch the MoinMoin wiki" project. This effort is approximately _infinite_ years overdue.
The guiding principles are to:
* add new content to our docs
* rewrite advice on the wiki to avoid copyright/contributor problems, and
* to remove pages from the wiki as these PRs land.
A lot of the information is "best practices" info, so I've added an entire new chapter for Best Practices.
This is the https://wiki.apache.org/couchdb/Working_with_Forms page, condensed to avoid redundancy.
Some of the information on the page is generally useful as JS development tips, so I started a new section for that as well.

Migrate working with forms from wiki, start JS dev tips page

---

src/intro/curl.rst
src/intro/index.rst

cURL should be explained before our first example that uses it.
On Windows, special escaping is required; explain the syntax necessary for beginners right at the start.

Bump curl earlier in intro, fix for Windows

---

src/best-practices/index.rst
src/best-practices/nginx.rst

Adds basic docs on using nginx as a reverse proxy.
Includes a nice header saying we still thing HAProxy is better.
This is part of the wiki migration project.

Add nginx docs

---

src/best-practices/documents.rst
src/best-practices/index.rst

Originally part of #275, but moved to a new PR for easier consideration in isolation, since the FAQ PR has become quite bloated.

Migrate some FAQ material to the Best Practices documentation

---

src/index.rst

`:numbered: 3` was invalid and Sphinx had started to blow up there because
there were fixes to the that part of the code:
https://github.com/sphinx-doc/sphinx/pull/4998/files

Fix sphinx 1.7.5 build

---

src/ddocs/ddocs.rst

This PR does two things: first, it expands the documentation of the existing builtin reduce functions to cover previously undocumented advanced behaviors for `_sum` and `_stats`, and generalizes the structure to allow for more builtins. Then, it leverages that generalization to introduce new documentation for the `_approx_count_distinct` builtin being developed in [COUCHDB-2971](https://issues.apache.org/jira/browse/COUCHDB-2971).
apache/couchdb#1346

Expand docs on builtin reducers, add _approx_count_distinct

---

src/config/couchdb.rst

The `[couchdb] default_security` setting is not documented except in [the source](https://github.com/apache/couchdb/blob/master/rel/overlay/etc/default.ini#L26-L31), so I wrote this patch.

Document the couchdb/default_security configuration setting

---

src/experimental.rst

Neither of these features made it into 2.x and should have been scrubbed from the docs a while ago.
Fixes #286.

Drop unsupported node query server, plugins from 2.x

---

.travis.yml
requirements.txt
src/cve/2018-8007.rst
src/whatsnew/1.7.rst
src/whatsnew/2.1.rst

This is a merge of the 2.1.2 release notes, and the build fix for https://github.com/sphinx-doc/sphinx/issues/5048 .
Because of our setup we're unable to merge from 2.1.x directly onto master (since the branch is forced to rebase from master before merging), so this is the cherry-picked commits from 2.1.x onto a new, updated branch.

2.1.2 release notes + fix the build

---

src/install/troubleshooting.rst

Documentation for https://github.com/apache/couchdb/pull/1445

Add troubleshooting information for FIPS mode and workaround (#1171)

---

src/api/server/configuration.rst
src/config/http.rst

Updating and clarifying the difference between `server_options` and `socket_options`. We still need to migrate some of this stuff from `httpd` to `chttpd` but that's not for this PR.
apache/couchdb#1411

Changes to match apache/couchdb#1411

---

src/best-practices/jsdevel.rst

This PR provides hope to developers learning of CouchDB's antique JavaScript engine, and the ancient JS dialect required therefore. 
Transpiling modern JavaScript for e.g. backwards browser compatibility is so common these days that it's arguably a fundamental skill for any front-end developer. The tooling and config that's needed, however, is NOT beginner-friendly, and so a link is provided to [Babel's in-browser real-time-transpilation text editing tool](http://babeljs.io/repl), as well as 2-step instructions on how to target the JavaScript version required by CouchDB's engine. 
In short, it informs users that modern JavaScript **can** be used, albeit with a little step in between.
N/A
N/A
N/A

Include info on JS transpilation with link to Babel's repl-editor

---

src/api/ddoc/rewrites.rst
src/best-practices/jsdevel.rst

Follow-up to https://github.com/apache/couchdb/issues/1410
I'm not sure which specific version of CouchDB rewrites-as-a-function was introduced, but it was sometime after CouchDB 2.0.0--hence the `2.x` moniker.
Updated it if you need more accuracy. 😄 
Cheers!
🎩

Fix version for rewrites as a function

---

src/api/server/common.rst
src/api/server/configuration.rst
src/config/http-handlers.rst
src/intro/security.rst

We need to be able to restart CouchDB from integration test suite.
We used to have this feature, but it was removed.
This PR documents `/_node/$node/_restart` endpoint implemented in 
https://github.com/apache/couchdb/pull/1543.
https://github.com/apache/couchdb/pull/1543

Document 'POST /_node/{node-name}/_restart'

---

src/config/http.rst

it's `changes_timeout`, not `changes_feed`.

feed->timeout bug, closes apache/couchdb#1592

---

src/api/database/common.rst

To document the availability of the `n=*` query parameter in the `PUT /{db}` REST method.

To document the availability of ?n=* in PUT /{db}

---

src/ddocs/ddocs.rst

missing semicolon before while loop.
##Overview
added missing semicolon before while loop in code example for list functions in the design document documentation.
without this semicolon compilation error will occur:
{"error":"compilation_error","reason":"Expression does not eval to a function. (...)}
##Testing recommendations
try copy pasting and minifying via for example at https://www.minifier.org/, write code directly into ddoc list function.

added missing semicolon in code example list

---

src/api/database/common.rst

```
line 158 : too long (173 > 90) line
:query integer n: Replicas. The number of copies of the database in the cluster. The default is 3, unless overridden in the :config:option:`cluster config <cluster/n>` .
```
This passes make check locally on MacOS but fails in Travis somehow.
Even stranger, it passed in Travis before when it was PR

Fix `make check` failure in api/database/common.rst

---

src/cluster/theory.rst

The doc said:
> If you have 4 shards, that means that you can have at most 4 nodes.
But at other places it states:
> For systems with lots of small, infrequently accessed databases, or
> for servers with fewer CPU cores, consider reducing this value to
> ``1`` or ``2``.
and:
> In a default 3-node cluster, each node would receive 8 shards.
From my understanding, the number of *shards* can be anything, and even
`q=1` will not alter safety of data. Only `n` can. If I understand
correctly:
- If you have 4 *copies* of a shard (`n=4`), that means that you can
have at most 4 nodes.
- The number of nodes is not impacted by the number of shards (`q`).
- You can have safe clusters with `n=3`, `q=1` (2 nodes can be down).
So this commit tries to make the doc clearer. -- Please tell me if I'm wrong!

Fix ambiguity in documentation on shards and replicas

---

src/ddocs/ddocs.rst
src/install/unix.rst
src/replication/protocol.rst

Remove broken links to previous CouchDB wiki (wiki.apache.org).
affected docs:
- src/ddocs/ddocs.rst 
- src/install/unix.rst
- src/replication/protocol.rst
Fixes #351 
- [] Documentation is written and is accurate;

Remove broken links to wiki.apache.org

---

.travis.yml
src/cluster/purging.rst
src/conf.py
src/config/auth.rst
src/ddocs/ddocs.rst
src/install/unix.rst
src/replication/protocol.rst
src/whatsnew/2.3.rst
src/whatsnew/index.rst

Time to add the 2.3.x release notes.
Read them and make comments!

Add 2.3.x release notes

---

src/whatsnew/2.3.rst

I noticed some errant whitespace was causing `make check` to fail while checking https://github.com/apache/couchdb-documentation/pull/354. This PR removes it.

fix: remove trailing whitespace

---

src/api/database/find.rst
src/cluster/sharding.rst

Oops, some syntax errors in the Shard Maintenance section meant that any code blocks weren't being displayed.

Fix RST syntax errors

---

src/config/intro.rst

This seems to be a discrepancy from the start, see original pull requests:
* https://github.com/apache/couchdb/pull/1095 (code)
* https://github.com/apache/couchdb-documentation/pull/227 (docs)
~~Note also the script seems unhappy with relative paths, so I've also snuck a wording change alongside the main fix here.~~ <ins>I've filed https://github.com/apache/couchdb/issues/1757 instead, and kept this patch focused on the incorrect ENV variable name</ins>

Startup script uses COUCHDB_ARGS_FILE for vm.args path

---

src/api/database/common.rst

There is a change in status codes returned by create/delete database operations
* PUT <db>
- Database creation returns 201 - Creation if the quorum is met
- Database creation returns 202 - Accepted if at least one node responds ok
- Database creation returns 500 - Error if there is no correct response from any node
* DELETE <db>
- Database deletion returns 404 - Not found if all nodes respond not found
- Database deletion returns 200 - OK if the quorum is met and at least one is ok
- Database deletion returns 202 - Accepted if the number of responses are bellow quorum and at least one is ok
- Database deletion returns 500 - Error in other cases
N/A
- https://github.com/apache/couchdb/pull/1139 (issue https://github.com/apache/couchdb/issues/1136):  Error 500 deleting DB without quorum
- …

Add new return codes for database creation/deletion

---

src/whatsnew/2.3.rst

Will contain the remainder of the 2.3.0 release notes.
Holding to merge until the last few issues are fixed for 2.3.0. Will be updated with each merged PR to apache/couchdb.

Update 2.3 release notes

---

src/api/database/common.rst

Change type of `purge_seq` from number to string.
```
jiangphs-mbp-2:couchdb-documentation jiangph$ make check
python ext/linter.py src/
```
https://github.com/apache/couchdb-documentation/issues/364

Change type of purge_seq from number to string

---

Makefile
src/best-practices/documents.rst
src/best-practices/reverse-proxies.rst
src/config/http.rst
src/config/query-servers.rst

* Typos and fixes from @flimzy reviews of the last PR
* Migrated "Apache as a reverse proxy", called out HAProxy more prominently as preferred solution
* Adding pointer to more Erlang query server examples
* Add link to (very old) video on vhost/rewrite behaviour
There are only a few pages left; I will probably finish migrating the wiki tomorrow :dancing_women:

More how tos

---

.travis.yml
ext/configdomain.py
ext/httpdomain.py
src/api/local.rst
src/cluster/index.rst
src/conf.py
src/config/index.rst
src/cve/index.rst
src/ddocs/views/intro.rst
src/ddocs/views/joins.rst
src/index.rst
src/install/troubleshooting.rst
src/intro/api.rst
src/intro/overview.rst
src/maintenance/index.rst
src/replication/conflicts.rst
src/replication/index.rst
src/setup/cluster.rst
src/whatsnew/index.rst
templates/layout.html
templates/pages/index.html

This is the last of the old wiki.apache.org content migration. This consisted of:
* whether or not to `emit(whatever, doc)` or not,
* how to debug CouchDB startup if it fails,
* the nature of CouchDB's transactional model (1 document = 1 transaction)
At the same time, I have:
* Added how to query conflicted docs in a DB using Mango (formerly this was only linked via the release notes)
* Added the registered trademark :registered: for Apache CouchDB in the footer/TOC/Title page
* Standardized the Table of Contents nomenclature
* Reorganised the ToC into major sections:
* User Guides
* Administration Guides
* Reference Guides
* Other
Would appreciate a cursory +1 from @janl since this is a big change to the Table of Contents.
Screenshot attached so you don't have to build it yourself...

Last wiki migrations; rework of TOC & headers

---

src/api/database/index.rst
src/api/database/shard.rst
src/cluster/sharding.rst

New: apache/couchdb#1807 's `/{db}/_sync_shards`
Previously undocumented: `/{db}/_shards` and `/{db}/_shards/{docid}`. These have been around since 2.0.

Document 1x new and 2x undocumented shard endpoints

---

src/config/compaction.rst

Since apache/couchdb@58fef34 "feat: bump the compaction daemon
check_interval to one hour", the default value is `3600`.
---
We had a hard time finding whether `check_interval` was waited between
*each database compaction*, or between *a whole compaction run for all
databases*.
I propose to make it very explicit.
---
This new parameter was introduced in apache/couchdb@e5bf9d4 "add
snooze_period doc to default.ini" and changed in apache/couchdb@5471694
"Add snooze_period_ms for finer tuning".

Update configuration of compaction daemon

---

.gitignore
README.md
src/config/cluster.rst

This fixes the broken reference to the PUT db API
`make html` and open `build/html/config/cluster.html` locally to confirm link works
Not sure if this is really passing though?
```
$ make check
python3 ext/linter.py src/
$ echo $?
0
```
FIxes #383

Config cluster ref fix

---

ext/linter.py
src/config/couchdb.rst
src/cve/2012-5641.rst
src/cve/2014-2668.rst
src/intro/curl.rst
src/replication/intro.rst

Recently I've noticed that sometimes, my local `make check` doesn't show any errors, but Travis does.
I finally traced this down to a logic error in how the "ignore errors for the next _n_ lines" parser worked.  Its `IGNORE_ERROR` flag wasn't being cleared if the "ignore errors for the next _n_ lines" directive was invoked, but no error appeared. Now, we always clear that flag correctly, and forcibly clear it when switching files to be 100% sure.
The problem was a Heisenbug because the directory traversal code can traverse directories in different orders, depending on how the `git clone` operation builds the directory tree. Fun!
Ironically, this bug only surfaced because I relaxed the max line length from 80 to 90 characters, so all of the current ignore directives in our code never …

Fix linter sometimes ignoring errors

---

src/setup/cluster.rst

Fixing a misspelled word: rage to range.

Fixing misspelled word

---

src/config/auth.rst

I discovered the new-ish `cookie_domain` setting kind of by accident. This adds a bit of documentation for it.
Does my writing make sense? Is the `versionadded` note correct?
https://github.com/apache/couchdb/pull/827

Mention [couch_httpd_auth] cookie_domain

---

src/config/http.rst

The [2.1 release notes](https://docs.couchdb.org/en/latest/whatsnew/2.1.html) mentioned fixing this parameter. I didn't even know it existed, but it's quite helpful to improve replication performance as `OPTIONS` requests can be cached.
Is it correct what I've written?

Mention [cors] max_age

---

src/config/couch-peruser.rst

There is no indication in the documentation that the existence of the `_users` database is a prerequisite to enabling `couch_peruser`. This note would have saved me quite a bit of time. 
Source of note is here: 
https://github.com/apache/couchdb/issues/749#issuecomment-322057875

Include note about enabling couch_peruser.

---

src/api/ddoc/common.rst
src/config/query-servers.rst
src/query-server/index.rst

This PR supplement query servers documentation so it is now more clear that since 2.3 environment variables only should be used.

updated query servers documentation

---

rfcs/template.md

This is the RFC template as agreed to over in the main repo, but now in the documentation repo, as agreed to by the dev list and RFC writers.
This is just a mechanical move, so I'll merge this without a +1.

Add new RFC directory with approved template

---

src/ddocs/ddocs.rst

Currently, there is no documentation on what denotes a design document in its documentation page. This pull request adds a brief "Creation" section to the documentation, explaining the concept of ```{"id": "_design/{name}"}```
This is a simple documentation addition. No additional testing steps should be necessary
N/A
N/A

Clarify how design documents are created

---

src/whatsnew/2.3.rst

The docs list a bugfix "Refuse building with known bad versions of Erlang" and incorrectly reference it as issue 1875, when it's actually issue 1857.

Correct "Refuse building with known bad versions of Erlang" issue number

---

rfcs/009-exunit.md

RFC for using ExUnit for unit tests
N/A
N/A
- Initial implementation of the RFC https://github.com/apache/couchdb/pull/2039

Add rfc for using ExUnit for unit tests

---

src/install/unix.rst

The acceptable version requirements pattern for Erlang is out of date.
This reflects our current supported Erlang versions.

Update our Erlang version requirements

---

src/config/auth.rst

This is a very over-due followup to https://github.com/apache/couchdb/issues/1598#issuecomment-419463294

Clarify what the allow_persistent_cookies config value does

---

src/api/database/common.rst
src/api/index.rst
src/api/partitioned-dbs.rst
src/index.rst
src/partitioned-dbs/index.rst
templates/pages/index.html

This is documentation for the new partitioned databases feature. It covers the new APIs as well as provides a guide on actually using the feature.
Um?
Main feature PR: https://github.com/apache/couchdb/pull/1789

Documentation for partitioned dbs

---

src/install/unix.rst

Every now and then someone hops into IRC, Slack or the mailing lists, who can't figure out how to install CouchDB from package correctly. Usually it's because they pasted without reading and substituting their platform correctly.
This makes the instructions overly explicit.
Oh, and this drops newly deprecated platforms and adds Debian 10 (buster) as supported.
Read it!
n/a
https://github.com/apache/couchdb-pkg/pull/49
https://github.com/apache/couchdb-pkg/pull/49

Improve UNIX binary package install instructions

---

src/api/database/common.rst
src/api/ddoc/common.rst
src/api/server/common.rst
src/config/compaction.rst
src/intro/security.rst
src/json-structure.rst
src/maintenance/compaction.rst
src/partitioned-dbs/index.rst
src/query-server/protocol.rst
src/replication/protocol.rst

We replaced the `disk_size` and `data_size` fields with the `sizes` object. This updates the documentation to remove all mention of those deprecated fields in preparation for their removal in 3.0.
apache/couchdb#2162
apache/couchdb#2163

Remove mention of old size fields

---

src/config/compaction.rst

Small fixup to use the correct field name

---

rfcs/004-document-storage.md

This document describes a data model for storing JSON documents as key-value
pairs in FoundationDB. It includes a discussion of storing multiple versions of
the document, each identified by unique revision identifiers, and discusses some
of the operations needed to query and modify these documents.

RFC for document storage

---

rfcs/001-fdb-revision-metadata-model.md

RFC for the storage of revision metadata in FoundationDB.
N/A
N/A
N/A

Add latest RFC draft for FDB revision storage

---

rfcs/011-opentracing.md

Collecting profiling data is very tricky at the moment.
Developers have to run generic profiling tools which are not aware of CouchDB specifics.
This makes it hard to do the performance optimization work. We need a tool which would
allow us to get profiling data from specific points in the codebase.
This means code instrumentation. This RFC proposes to add opentracing support to CouchDB.
- [Discussion on ML](https://lists.apache.org/thread.html/36646da2bf96dd99303aa80d6bba4063b6210d7934d57735c89e1425@%3Cdev.couchdb.apache.org%3E)
- [Some thoughts on configuration aspect](https://gist.github.com/iilyak/ff4733898b1a82963a0607a61d65fe1d)

RFC-011 : Opentracing support

---

src/install/troubleshooting.rst
src/maintenance/performance.rst

ERL_MAX_PORTS affects the number of Erlang ports allowed at once, and
defaults to 1024. An Erlang port is created via erlang:open_port and
is used to launch an executable like couchjs. It is not, directly, a
limit on TCP sockets or file descriptors.

Correct misleading commentary on ERL_MAX_PORTS

---

src/install/troubleshooting.rst
src/maintenance/performance.rst

This reverts commit f6b5f742f0f6d337b2c9895b3f42d8b05533a695.
I was wrong.

Revert "Correct misleading commentary on ERL_MAX_PORTS"

---

src/api/database/bulk-api.rst
src/api/database/common.rst
src/api/database/compact.rst
src/api/document/attachments.rst
src/api/document/common.rst
src/api/server/configuration.rst
src/config/couchdb.rst
src/maintenance/performance.rst
src/replication/protocol.rst

Issue: https://github.com/apache/couchdb/issues/2165
The code was removed on master for 3.0 in https://github.com/apache/couchdb/pull/2208

Remove delayed commits

---

src/api/database/bulk-api.rst
src/install/unix.rst

Added the following status codes in the documentation where they were missing:
* `{db}/_find` - 404
* `{db}/_bulk_docs` 404
* `{db}/_all_docs` `GET` 200, 404
* `{db}/_all_docs` `POST` 404
* `{db}/_design_docs` `GET` 404

Added some missing status codes

---

src/install/docker.rst
src/install/kubernetes.rst

Adds a page with reference to the CouchDB helm chart. Given the
instructions for the Helm chart vary by release and are embedded
in each chart, I delegated to Helm Hub for the full configuration
/ documentation.

Add Kubernetes install instructions

---

src/api/ddoc/common.rst

Background indexing in CouchDB can be controlled on a
per-design document basis. This documents the option to
disable automatic indexing by specifying `autoupdate: false`
as a top level field in a design document.
n/a
#439

Add autoupdate field to design docs API

---

src/api/database/bulk-api.rst
src/api/local.rst

In apache/couchdb#2343 the way POST _all_docs works is altered so that the same functionality is available as in GET view.
This commit updates the POST _all_docs documentation to reflect this new behavior.
This depends on apache/couchdb#2343 .
Execute the tests seen in apache/couchdb#2343 .
* apache/couchdb#2343

All docs post all params

---

src/api/server/common.rst
src/replication/replicator.rst

Companion to the implementation PR https://github.com/apache/couchdb/pull/2379
The value of the `"info"` field from the _scheduler/* API cannot be a string anymore. It is now restricted to be a `null` or a JSON object. 
https://github.com/apache/couchdb/pull/2379

Switch replicator "info" error message to be an object

---

src/api/database/find.rst

Comparison of strings with mango selectors `$gt` and `$lt` and be surprising. Let's add a warning about that.

Add a warning for $lt and $gt with strings

---

src/config/index.rst
src/config/ioq.rst

This PR is a little bit different. It is not an accurate description of the current configuration for IOQ (which is far less coherent), but is rather an attempt to write down what I think the configuration ought to look like when we release 3.0. I've gone back and forth several times on how much we ought to modify and enhance IOQ at this late juncture, and figured one way to unblock things was to document what a sensible future state would look like.
The system I've documented here can be implemented with a conservative patch on top of the IOQ implementation that was present in CouchDB 2.3.1; i.e., it would ignore the "full fat" IOQ system later contributed by Cloudant. I expect that this approach will yield a higher-throughput system than "IOQ1" contributed by Cloudant and will be far …

Document the IO Queue system

---

src/api/server/common.rst
src/api/server/configuration.rst
src/config/misc.rst

Documents the `stats.interval` configuration key and remove
the redundant `rate` and `samples` keys.
Additionally, adds a note about how `histogram` types interact
with the collection interval and how `_stats` should be safely
consumed to avoid lossy sampling.
n/a

Update _stats configuration

---

src/config/query-servers.rst

Adds documentation for the Mango configuration options:
* mango.index_all_disabled
* mango.default_limit
* mango.index_scan_warning_threshold

Document Mango configuration options

---

src/config/cluster.rst

Document the config flags for the RPC library
apache/couchdb#2360 is a new config setting for 3.0

Document rexi config settings

---

src/config/auth.rst

Add documentation for configuring the SameSite attribute of the
auth cookie.
Refs #2221
https://github.com/apache/couchdb/pull/2452

Document same_site cookie attribute

---

src/api/server/common.rst
src/intro/api.rst

Followup from [this slack conversation](https://couchdb.slack.com/archives/C49LEE7NW/p1562409911483700) with @janl, to update the replication documentation for the new post-2.x requirement for full URLs in replication source and target.

Update local replication documentation

---

src/api/server/configuration.rst

Add documentation for the _node/<node>/_config/_reload endpoint.
n/a
https://github.com/apache/couchdb/pull/2475

Document _config/_reload endpoint

---

src/api/server/common.rst

The response description for `_scheduler/docs` says there's a key `last_update`, however there isn't one. There is a `last_updated` instead, just as it shows in the example right below.
This change fixes the issue described above.
Query `_scheduler/docs` and observe the response.

Fix typo in `_scheduler/docs`

---

src/api/basics.rst
src/api/ddoc/common.rst
src/api/ddoc/render.rst
src/api/ddoc/rewrites.rst
src/config/http.rst
src/ddocs/ddocs.rst
src/intro/security.rst
src/query-server/index.rst
src/query-server/protocol.rst
src/whatsnew/3.0.rst

Completion of the deprecation work mentioned in https://github.com/apache/couchdb/issues/2218 (thanks for the list @iilyak !)

Deprecate show, list, rewrite, vhosts

---

src/best-practices/reverse-proxies.rst
src/config/auth.rst
src/config/http.rst
src/intro/api.rst
src/intro/curl.rst
src/intro/index.rst
src/intro/security.rst
src/intro/tour.rst
templates/layout.html

This attempts to put passwords in all our examples in the intro at least, and remove references to admin party elsewhere.
Ignore the branch name ;)

Fully remove mention of admin party everywhere

---

src/whatsnew/3.0.rst

There's still 2 TODOs in here:
* Link to fauxton changes (have pinged Fauxton people to help over here: https://github.com/apache/couchdb/issues/2509
* Link to dreyfus installation info (#474 )
Please review the changes so far, though.

More 3.0 release notes

---

src/install/windows.rst
src/whatsnew/3.0.rst

Since we're cutting 3.0.0-RC2...let's document the Windows installer improvements.
We'll then tag this as `3.0.0-RC2` and we can reference that in `rebar.config.script` instead, which allows us to move `3.0.0` if we need to.

Document Windows installer improvements

---

src/install/windows.rst
src/whatsnew/3.0.rst

* Fix typos
* Make need for .NET Framework v3.5 on Win 8/8.1/10 louder
* Explain SM 1.8.5 vs. 60 situation in a bit more detail

Clarifications in 3.0 relnotes

---

README.md

Remove outdated reference on `virtualenv` and Python 2.7
Go through the documented steps.

Update Getting Started section in Readme

---

src/api/database/bulk-api.rst

The example result for _all_docs/queries did not match the example request and it was incorrect in a sense that the values `id` fields were not matching the respective values of `key` fields and there was a document returned that was not specified in the query.
This change fixes the issue described above by editing the ids so that they match the keys now and removing the element that was not specified in the request.

Fix _all_docs/queries example result

---

src/config/indexbuilds.rst

When looking for ways to control background indexing, users usually land on [3.8. Background Indexing](https://docs.couchdb.org/en/3.0.0/config/indexbuilds.html).
But if they are looking for a way to disable background indexing of a specific ddoc or view, that option (`autoupdate`) is documented in the [ddoc API](https://docs.couchdb.org/en/3.0.0/api/ddoc/common.html#put--db-_design-ddoc).
This pull request adds a note about `autoupdate:false` and a link from background indexing to the ddoc API.
Decide if a `Note` or `See also` is more appropriate.
There is no bug. It is probably not a significant change.

Add note of ddoc autoupdate:false to ken config

---

src/api/document/attachments.rst

According to https://docs.couchdb.org/en/stable/api/document/attachments.html#put--db-docid-attname Content-Type is a required header in case of adding new attachment.
However, attachments can be created without specifying the content type
Create attachment without providing Content-Type header.
Eg:
```
$ curl -X PUT -v 172.17.0.2:5984/mydatabase/doc4/aab.jpg  --upload-file README.txt 
{ [67 bytes data]
{"ok":true,"id":"doc4","rev":"1-8a5b4ad6f236295aeb5a52edb8f27470"}
100  5956  100    67  100  5889   2310   198k --:--:-- --:--:-- --:--:--  207k
* Closing connection 0
```
Fixes #507 Content-type header is not required when putting attachments

Fix PUT attachment documentation

---

src/maintenance/compaction.rst

Docs bump for the change in https://github.com/apache/couchdb/pull/2678 .

New smoosh defaults for 3.0.1

---

src/api/server/authn.rst
src/config/auth.rst

Documentation for the optional JWT authentication handler
N/A.
N/A
https://github.com/apache/couchdb/pull/2648

JWT documentation

---

src/whatsnew/3.0.rst

3.0.1 release notes.
After this lands, we'll need to tag (and probably fork) for 3.0.x docs so we can get the 3.1.0 docs out.
CI

Add 3.0.1 release notes

---

src/install/search.rst

Added a sentence n explicitly setting the classpath in te server parameters when running the service.
Issue `[511](https://github.com/apache/couchdb-documentation/issues/511)` asks for elaboration of the Search Plugin documentation page. This pull request amends the current documentation.
Check out the 511-extend-clouseau-pugin-doc branch and run Sphinx to generate the documentation. 
`make check` should have no output.
Go to the couchdb-documentation/build/html/install/search.html#install-search and see the result in the browser.
Fixes [511](https://github.com/apache/couchdb-documentation/issues/511)

511 extending clouseau plugin doc

---

src/install/unix.rst

CouchDB 3.1.0 can be installed directly on Focal, update the docs to show this is possible now.

Update install instructions for focal

---

src/api/server/common.rst

This PR intended to solve the missing document modifications from https://github.com/apache/couchdb/issues/2497. (Unfortunately, GitHub does not allow me to open the issue).
As per the 3.0.1 upgrade notes says
> The setup wizard no longer automatically creates the `_global_changes` database, as the majority of users do not need this functionality. This reduces overall CouchDB load.
If I am correct this means the default values of the `ensure_dbs_exist` property reduced from `["_users","_replicator","_global_changes"]` to `["_users","_replicator"]` at the `/_cluster_setup`. Moreover `/_db_updates` cannot be reached till the `_global_changes` database is not created beforehand.

Correct the occurrence of _global_changes

---

src/install/docker.rst

This will prevent us from having to bump the versions in this section again until 4.0.

Freshen Docker install info

---

rfcs/015-background-index-building.md

This RFC describes how background index building works in CouchDB 4

[RFC] Background index building in CouchDB 4

---

src/partitioned-dbs/index.rst

I assume the author intended to write that sensor_id was the partition key, since it doesn't make sense to me how a field could be a partition.

Add missing word "key" in "What is a partition?"

---

src/install/unix.rst

Remove apt-transport-https from to-be-installed packages for Debian >= 10 and Ubuntu >= 18.04, since that functionality has been moved into the main apt package and apt-transport-https became a dummy package.

apt-transport-https has become a dummy package as of Debian 10/Ubuntu 18.04.

---

src/config/replicator.rst

Adds `max_history` parameter to documentation for configuring replicator database.
Cross-referencing with main CouchDB repo shows that `max_history` is a configurable parameter in CouchDB 3.1. (see [couch_replicator_scheduler#L238](https://github.com/apache/couchdb/blob/4e64f5b492990b03f7f58a47ec173d048a3f381f/src/couch_replicator/src/couch_replicator_scheduler.erl#L238)). 
While researching CouchDB's offline-first functionality in environments of low and/or intermittent connectivity, one of the main issues was the possible length of the delay between replication jobs due to the exponential back-off algorithm. In environments where users have unreliable and intermittent connectivity, it is important that replication restarts quickly when network connectivity is established.
One possible …

Add max_history to replicator config

---

src/install/unix.rst

* `tee -a` could leave behind old info in debian apt files, remove -a
* added RH8
Comes after giving advice in https://github.com/apache/couchdb/discussions/2954

Improve binary installation procedure

---

src/ddocs/search.rst

To use multiple `drilldown` parameters users had to define
`drilldown` multiple times to be able supply them.
This caused interoperability issues as most languages require
defining query parameters and request bodies as associative
arrays, maps or dictionaries where the keys are unique.
This change enables defining `drilldown` as a list of lists so
that other languages can define multiple drilldown keys and values.
`make check` passed for me locally
This is related to https://github.com/apache/couchdb/pull/2958

Allow drilldown for search to always be specified as list of lists

---

src/config/http.rst

Add JWT authentication as an option in the list under the 'authentication handlers' section in the docs

Add JWT authentication to list in docs

---

src/ddocs/ddocs.rst

A simple mistake in the key name in a ddoc example.

Key name correction in ddoc example

---

src/install/troubleshooting.rst

Our advice on bumping file handles for CouchDB was out of date. `ERL_MAX_PORTS` was replaced by `+Q` multiple versions ago, and the version of Erlang we ship now in our packages doesn't even support it.
This clarifies the advice and adds some additional useful context.
Relates to https://github.com/apache/couchdb-pkg/pull/70

Improve advice on running out of file handles

---

src/maintenance/performance.rst

More stuff following on from #566

Further improve fd limit increase docs

---

src/api/database/misc.rst

In the return object of `POST /{db}/_missing_revs` there is no `missed_revs` field.
`missing_revs` field is returned.
Send a `POST /{db}/_missing_revs` request and the response object will contain `missing_revs` field.

Rename missed_revs to missing_revs in {db}/_missing_revs result

---

src/api/database/find.rst

Documentation of a newly proposed Mango query operator that allows to make queries on the keys of a map.
For the example I stayed in the filmography theme, it is supposed to mean : 
match all documents where the `cameras` field, which is a map, has a key equal to `secondary`. 
I don't know if the query examples for the operators are related to a representation of a document somewhere that should also be updated ?
https://github.com/apache/couchdb/pull/3041

New Mango operator documentation (match keys of a map)

---

src/api/ddoc/views.rst

Fixes a small typo in `src/api/ddoc/views.rst`. Not sure if the wording as I've put it is correct, but given that there are probably multiple ICU drivers in existence, I'd wager it is.

fix(api): Fix typo in ddoc/views.rst

---

src/config/auth.rst

Accurately describe what persistent_cookies = true does.
N/A
N/A

Persistent cookies accurate description

---

src/install/windows.rst

Quick example of how to install CouchDB on Windows to a custom directory from the command line, unattended.
See https://github.com/apache/couchdb-pkg/issues/71 for discussion

Show unattended install to custom path on Windows

---

src/intro/security.rst

This follows up on: https://github.com/apache/couchdb/issues/3084, https://github.com/apache/couchdb/issues/2881 and https://github.com/apache/couchdb/issues/2730#issuecomment-606828007
In my particular case we had the team bug hunting for a few hours because we were sure this particular sentence meant the security behavior of `_users` would have been preserved in Couch 3 when it's not. So maybe it helps others if they aren't given the chance to misunderstand this.
---
As for the edit, I tried rephrasing the sentence but couldn't come up with anything without the potential of misunderstanding, so I think removing it in its entirety is the safest bet. If you have any idea of how to keep it, but make it clearer I'd be happy to learn about it.

Remove misleading sentence about how users can browse their own user docs

---

src/api/database/bulk-api.rst

In the CouchDB documentation related to `POST /{db}/_design_docs` there is an issue on the request example.
This PR change `POST /db/_all_docs HTTP/1.1` to `POST /db/_design_docs HTTP/1.1` in the request example.

Fix example request for `POST /{db}/_design_docs` in documentation

---

src/api/database/find.rst
src/api/ddoc/views.rst
src/maintenance/performance.rst

The docs for `stale` in views don't match the current behavior of the software.
This PR fixes that issue by removing `false` from the available options from `stale` for views.
Mind that, the "default value" (`false`) for `stale` can no longer be expressed explicitly.
```python3
print(requests.get(f"http://127.0.0.1:15984/{db_name}/_all_docs?stale=false", auth=('adm', 'pass')).json())
```
results in
`{'error': 'query_parse_error', 'reason': 'Invalid value for `stale`.'}`
This is a follow-up PR for https://github.com/apache/couchdb/pull/3120 .

Fix stale options

---

src/api/database/find.rst

This PR changes the API documentation for `/db/_find`.
It replaces all keys `$title` with `title`.
None
Accommodates expected behavior from https://github.com/apache/couchdb-documentation/issues/590
None

Removed $ from /db/_find in two places

---

src/api/server/common.rst

Pretty self-explanatory. Simple typo fix.

Fix spelling/typo mistake in /_up endpoint description

---

src/config/couchdb.rst

This has been wrong for at least 5 years per https://github.com/apache/couchdb/blame/main/src/couch/src/couch_file.erl#L286 .

Correct mistake on enable_database_recovery

---

src/api/basics.rst

CouchDB returns default headers `X-CouchDB-Body-Time` and `X-Couch-Request-ID`. This PR adds docs for them.
https://github.com/apache/couchdb/issues/3261
https://github.com/apache/couchdb/pull/3279 and https://github.com/apache/couchdb/pull/3281

Add missing default headers to responses

---

src/intro/security.rst

Adds a few missing updates/details regarding password fields within user doc, including:
1. `salt` field is used for **both** password schemes, not just ``simple``.
2. ``pbkdf2`` scheme also needs an `iterations` field
3. Added quick tip re. plaintext `password` field as well.

Update user doc password field details

---

rfcs/014-pagination.md

The main driver for this proposal is the introduction of FoundationDB as a
storage engine. FoundationDB imposes limits on transaction duration and size.
Therefore we need to find way to restrict amount of data we return to customers.
We could simply set the maximum `limit` which would cap amount of rows client can
request. However this "solution" has a big disadvantage. Which is it would require
clients to write pagination recepy in their code. Current pagination scheme
requires complex logic on the client side. There are quite a few corner cases
to handle.
N/A

Add pagination proposal

---

src/api/database/find.rst
src/api/server/common.rst
src/conf.py

I am opening this pr in reference to #598 
I've updated the following:
1. added a missing status code (404) 
2. removed `partial_filter_selector` from the query parameters (since it should be a property of the `index` parameter)
3. updated the `index` query parameter (it is no longer a list of strings but a json object)
4. changed the example that showcases the use of all query parameters
Use any tool to send a http request to couchdb using the example given in the pr. I've tested it with Couch DB 3.1.1 and get the following response:
```
result": "exists",
"id": "_design/example-ddoc",
"name": "example-index"
}
```
(I've run multiple tests that's why the index already exists)

Update for POST /{db}/_index

---

src/api/server/authn.rst

The instructions for creating the HMAC token (recommended for proxy authentication) aren't specific enough for developers to actually create a token from a username and secret. This PR clarifies the instructions, adds an example (using openssl) of creating the token and then adds it to the example HTTP request.
- Make sure documentation and syntax highlighting look okay on webpage
- Check that the example openssl command works and produces the same HMAC

More specific instructions for creating Proxy Authentication token

---

src/intro/security.rst

CouchDB 3.0 no longer allows users to access or modify documents in the `_users` database. This PR changes the Introduction documents to reflect those changes.
- I kept the existing information on 2.0 behaviour (users can access their own documents) but mentioned that it needs a change in settings, and will not be possible in 4.0. This is mentioned in a note so that it is easy to remove for 4.0.
- I removed the Users Public Information section which seems to revolve around a use case where users access documents in `_users`. This change is in a separate commit so it can be easily undone if deemed necessary.
- #513 mentions mandatory fields, but as far as I can tell the documentation on that is not strictly incorrect. The fields related to passwords and salts are generated automatically, …

Update docs regarding users' ability to access the _users database.

---

src/config/http.rst

Link to the CouchDB wiki SSL walkthrough. Closes #606

Link to the CouchDB wiki SSL walkthrough. Closes #606

---

src/config/http.rst

This addresses #628.
The problem with documenting the per-request `?buffer_response=true` option is that it would apply to any chttpd request that uses `delayed_json_response`. That could be very many.
For now, I've documented that this is an option within the config section. If someone wants to put together a full list of queries that would benefit from the additional argument, I'm happy to cut & paste the right text everywhere... but I also think this is "good enough for now.
/cc @janl you brought this issue over to docs 2 weeks ago, from Slack -- is this a sufficient docs improvement? If so we can say "this closes #628".

Add [chttpd] buffer_response option

---

src/setup/cluster.rst

Following the clustering guide, I found out that running the connectivity erlang command between nodes using an IP address will fail with like
```
(bus@10.20.30.40)1> net_kernel:connect_node(car@10.20.30.50).
* 1: syntax error before: '.'
```
if the `node_name@ip` contains single quotes will work
```
(bus@10.20.30.40)1> net_kernel:connect_node('car@10.20.30.50').
true
```
As the documentation doesn't contain single quotes, I recommend adding them (the actual example fails as it is as it contains an IP)
Follow the clustering guide `2.2.2.2. Confirming connectivity between nodes`

Fixing erlang command to test connectivity between nodes

---

src/install/unix.rst

Bintray is deprecated and going away at the end of April. We now have new repos at JFrog Artifactory. 
This updates the documentation with pointers to the new repos, and an improved installation workflow.
Try installing packages on any of the supported operating systems:
* CentOS / RHEL 7 or 8
* Debian stretch or bsuter
* Ubuntu 16.04 (xenial), 18.04 (bionic), 20.04 (focal)
You could test this easily in docker with any of:
```
docker run -it centos:7
docker run -it centos:8
docker run -it debian:stretch
docker run -it debian:buster
docker run -it debian:stretch
docker run -it ubuntu:xenial
docker run -it ubuntu:bionic
docker run -it ubuntu:focal
```
and just follow the directions in the PR revised text.
Fixes apache/couchdb#3478
I will need to make this change to our stable tag as well, …

Update docs for new binary location

---

src/partitioned-dbs/index.rst

Added a small note in the What is a partition section introducing the reader to the ``max_partition_size`` option. This small note should make it clear that the default limit (and not just a recommendation) for partitions is 10gb but can be changed or disabled accordingly as mentioned in issue #661

Added a note regarding max_partition_size in index.rst

---

src/install/unix.rst

The installation guide made it seem like you still need mozjs 1.8.5 to build, but newer versions are now supported
Render docs

Update supported spidermonkey versions

---

src/install/unix.rst

Add 23 and 24
Issue: https://github.com/apache/couchdb/issues/3571

Remove 19.x from the list of supported versions

---

src/api/basics.rst
src/api/database/changes.rst
src/api/server/authn.rst
src/api/server/configuration.rst
src/config/auth.rst
src/config/couchdb.rst
src/config/http.rst
src/config/intro.rst
src/intro/security.rst
src/setup/cluster.rst
src/whatsnew/1.4.rst
src/whatsnew/2.1.rst
src/whatsnew/3.2.rst
src/whatsnew/index.rst

Modify the documentation about the moved configuration options.
Add 3.2.rst, maybe need more info for it. (Performance, Bugfixes, Features, Enhancements, etc.)
[#3472](https://github.com/apache/couchdb/issues/3472)
[#3567](https://github.com/apache/couchdb/pull/3567) Move config options from `[httpd]` to `[chttpd]`
[#3577](https://github.com/apache/couchdb/pull/3577) Move config options from `[couch_httpd_auth]` to `[chttpd_auth]`

Move some config options from [httpd] to [chttpd], from [couch_httpd_auth] to [chttpd_auth]

---

README.md
src/contributing.rst
src/install/unix.rst
src/replication/protocol.rst

- Fix broken couch_replicator link on [2.4. CouchDB Replication Protocol](https://docs.couchdb.org/en/latest/replication/protocol.html)
- Fix broken README.Debian link on [1.1. Installation on Unix-like systems](https://docs.couchdb.org/en/latest/install/unix.html)
- Switch contributing guide to use main instead of master branch
- Remove build state badge in README that points to what appears to be no longer used Travis CI project

Fix broken links, defunct Travis CI project, and contributing guide branch names

---

src/api/database/changes.rst
src/api/database/find.rst
src/api/database/misc.rst
src/api/ddoc/common.rst
src/api/ddoc/render.rst
src/api/ddoc/views.rst
src/api/document/attachments.rst
src/api/document/common.rst
src/api/local.rst
src/api/server/authn.rst
src/api/server/common.rst
src/config/compaction.rst
src/config/couchdb.rst
src/config/http.rst
src/config/query-servers.rst
src/ddocs/views/pagination.rst
src/intro/api.rst
src/maintenance/compaction.rst
src/maintenance/performance.rst
src/partitioned-dbs/index.rst
src/replication/intro.rst

As mentioned in #525, I have replaced the single back-ticks to double back-ticks **only in the file `src/api/server/authn.rst`**. I have modified all the instances which was resulting in italicisation. But I noticed that the single back-ticks have been used in a lot of other files.
Please let me know if all the files need to be updated. I'll update the pr with the same.
Thank you in advance!
Fixes #525

Use double back-ticks in src/api/server/authn.rst

---

src/api/database/security.rst

Just clarified the section a little with information from slack

Clarified default behavior of authorization to databases

---

src/config/auth.rst

Add documentation for the new `[couch_httpd_auth] password_regexp` config added in apache/couchdb#3483.
apache/couchdb#3483.

Add documentation for password_regexp

---

src/api/server/common.rst

Document the `selector` field of the `/_replicate` API.
- Create a db `a` and a db `b`.
- Create two document in db `a`.
- Replicate using `/_replicate` from db `a` to `b` with the the `selector` field set, where one doc does not pass.
- Check if only one doc exists in db `b`.
None.

Update common.rst to add selector to _replicate

---

src/whatsnew/3.2.rst

Add `password_regexp` to 3.2 release notes.

add password regexp to 3.2 notes

---

requirements.txt
src/conf.py

Bump sphinx requirements up enough until can build without warnings
This fixes the build https://readthedocs.org/projects/couchdb/builds/15156367/ (compare with https://readthedocs.org/projects/couchdb/builds/15149238/)
Results https://docs.couchdb.org/en/try-to-fix-readthedocs-build/

Try to fix readthedocs build errors

---

src/cluster/sharding.rst

This ensures that people who are blindly copy-pasting commands
don't accidentally delete running reshard jobs.
Signed-off-by: Rob Thomas <xrobau@linux.com>

Provide safer command to delete sharding jobs

---

src/api/server/common.rst

Update the Notes section for /_dbs_info to include advise on keeping the db limit to 100.

Update notes for /_dbs_info

---

src/api/ddoc/views.rst

Meanwhile, the documentation says `collation` should be set to `raw` in the root of the design document's `options` object, actually, it can be set under the view object where `options` will be a sibling of the `map` and `reduce` fields:
```json
{
"_id":"_design/doc",
"views": {
"myview1": {
"map": "function(...) {}",
"options": {"collation" : "raw"}
}
}
}
```
This is misleading, because design doc root also can have an `options` object, but the children of that object can be  `include_design`, `local_seq`, and `partitioned`.
No
not a significant change
no
I tested with `make check`.

Fix statement around collation

---

src/api/server/common.rst

Add `GET _dbs_info` API
It can accept `startkey/endkey/limit/skip` query string parameters as support for the existing `GET _all_dbs` API endpoint.
https://github.com/apache/couchdb/pull/3832

Add documentation for GET `_dbs_info`

---

src/conf.py

Python black removed Python 2 support so it now flags the `u` prefixed strings.
We picked up python black 22.1:
```
Collecting black
Downloading black-22.1.0-py3-none-any.whl (160 kB)
```
It removed python 2 support:
* https://pypi.org/project/black/22.1.0/
* https://github.com/psf/black/pull/2740

Reformat src/conf.py to conform to latest python black rules

---

src/install/unix.rst

Update dependencies and list of debian distributions.
Updating libraries for python3.10 https://github.com/apache/couchdb/pull/3980 revealed stretch uses python 3.5 which is very far out of date and stretch is no longer officially supported.

Unix Install freshen dependencies/distribution requirements

---

src/config/logging.rst

Add configuration infos for rsyslog to enable logging to facility
https://github.com/apache/couchdb/issues/3882

Add infos about enable logging over UDP in rsyslog

---

src/install/unix.rst

For building from source on Fedora, additional steps are needed. This documents those.

docs: additional build instructions for Fedora 36

---

src/api/database/find.rst

The docs currently don't contain much guidance on the performance of _find, which can lead new users down the wrong path.

Notes _find performance difference between custom indexes and _all_docs

---

src/maintenance/compaction.rst

Some users that we worked with reported compaction running outside of the compaction window configured with `to` `from` `window` options and that was causing confusion and after we looked into the issue and the couchdb code [here](https://github.com/apache/couchdb/blob/3.x/src/smoosh/src/smoosh_channel.erl#L113-L119)
This is just a note to clarify why some compaction process might be found running outside of the defined compaction window

Add note to clarify compaction window process

---

src/api/basics.rst

Documents when HTTP status 503 Service Unavailable is returned, and what the client should do. 
Based on 
```
error_info({error, security_migration_updates_disabled}) ->
{503, <<"security_migration">>, <<
"Updates to security docs are disabled during "
"security migration."
>>};
error_info(all_workers_died) ->
{503, <<"service unavailable">>, <<
"Nodes are unable to service this "
"request due to overloading or maintenance mode."
>>};
error_info({service_unavailable, Reason}) ->
{503, <<"service unavailable">>, Reason};
```
as unearthed by @rnewson

Documents when HTTP status 503 Service Unavailable is returned

---

src/cluster/sharding.rst

The q value for a peruser database depends on both the global q parameter and [peruser] q, if set.

In "Shards and Replicas", notes effect of [peruser] q config
